// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

/**
 * @title IInvestmentStrategy
 * @notice Standard interface for all Sharia-compliant investment strategies
 * @dev All strategies must implement this interface to be compatible with StrategyManager
 *      Strategies generate returns through halal means: profit-sharing, fees-for-service, trading
 */
interface IInvestmentStrategy {

    // =========================================================
    //                        EVENTS
    // =========================================================

    event Invested(uint256 amount, uint256 timestamp);
    event Withdrawn(uint256 amount, uint256 timestamp);
    event ReturnsEarned(uint256 amount, uint256 timestamp);
    event ReturnsClaimed(uint256 amount, address recipient, uint256 timestamp);

    // =========================================================
    //                    CORE FUNCTIONS
    // =========================================================

    /**
     * @notice Deploy capital into the strategy
     * @param amount Amount of HAL-GOLD to invest
     * @return actualInvested Actual amount invested (may differ due to slippage/limits)
     */
    function invest(uint256 amount) external returns (uint256 actualInvested);

    /**
     * @notice Withdraw capital from the strategy
     * @param amount Amount to withdraw
     * @return actualWithdrawn Actual amount withdrawn
     */
    function withdraw(uint256 amount) external returns (uint256 actualWithdrawn);

    /**
     * @notice Claim accumulated returns and send to StrategyManager
     * @return claimedAmount Total returns claimed
     */
    function claimReturns() external returns (uint256 claimedAmount);

    /**
     * @notice Emergency withdraw all funds (override normal limits)
     * @dev Only callable by admin in emergency situations
     * @return withdrawnAmount Total amount withdrawn
     */
    function emergencyWithdraw() external returns (uint256 withdrawnAmount);

    // =========================================================
    //                    VIEW FUNCTIONS
    // =========================================================

    /**
     * @notice Get total balance deployed in strategy
     * @return Total HAL-GOLD equivalent value in strategy
     */
    function getBalance() external view returns (uint256);

    /**
     * @notice Get total returns earned (lifetime)
     * @return Total profits generated by strategy
     */
    function getTotalReturns() external view returns (uint256);

    /**
     * @notice Get pending unclaimed returns
     * @return Accumulated profits waiting to be claimed
     */
    function getPendingReturns() external view returns (uint256);

    /**
     * @notice Get estimated Annual Percentage Yield
     * @return APY in basis points (e.g., 1200 = 12%)
     */
    function getAPY() external view returns (uint256);

    /**
     * @notice Check if strategy is Sharia-compliant
     * @return true if compliant, false otherwise
     */
    function isShariaCompliant() external view returns (bool);

    /**
     * @notice Get human-readable strategy name
     * @return Strategy name
     */
    function strategyName() external view returns (string memory);

    /**
     * @notice Get the asset this strategy invests (should be HAL-GOLD)
     * @return Asset token address
     */
    function asset() external view returns (address);

    /**
     * @notice Check if strategy is active and accepting investments
     * @return true if active
     */
    function isActive() external view returns (bool);
}
